# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RwXkgrEBzsSKmmWRL3-iH_eDHnKAIfP2
"""

import av
import cv2
from ultralytics import YOLO
from streamlit_webrtc import webrtc_streamer, VideoProcessorBase
import streamlit as st

st.set_page_config(page_title="Detector IA", layout="wide")

st.title("🗑️ Detector de Residuos IA")

# Cargar modelo
modelo = YOLO("best.pt")

confianza = st.sidebar.slider(
    "Confianza",
    0.1,
    1.0,
    0.4,
    0.05
)

class Detector(VideoProcessorBase):

    def recv(self, frame):

        img = frame.to_ndarray(format="bgr24")

        resultados = modelo.predict(
            img,
            conf=confianza,
            verbose=False
        )

        salida = resultados[0].plot()

        return av.VideoFrame.from_ndarray(
            salida,
            format="bgr24"
        )

camara = st.sidebar.selectbox(
    "Selecciona la cámara",
    ["Trasera", "Delantera"]
)

if camara == "Trasera":
    video_constraints = {
        "video": {
            "facingMode": {"ideal": "environment"}
        },
        "audio": False
    }
else:
    video_constraints = {
        "video": {
            "facingMode": "user"
        },
        "audio": False
    }

webrtc_streamer(
    key="detector",
    video_processor_factory=Detector,
    media_stream_constraints=video_constraints,
    async_processing=True
)